name = "agent-multiplayer"
workers_dev = true
compatibility_date = "2023-06-01"
# Add your account ID here

main = "src/main.ts"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "Room" }
]

# [[rules]]
# type = "Data"
# globs = ["**/*.html"]
# fallthrough = false

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room"]